### ISSUE TITLE
Handle NaN values gracefully

### ISSUE THREAD

**Issue by CheeriosJo** [memsql/memsql-statsd#1]
Currently, when statsd data comprised of NaN values, memsql-statsd backend just throw an error to the entire multi-insert statement, causing us a lot of data loss. 

2014-12-10 00:00:16 ERROR: Compilation of 
 [INSERT INTO `dashboard`.analytics (classifier_id, value, created) VALUES (6467643635036667000,0,1418187616),(14454896275846849000,0,1418187616),(4432973534098752500,479,1418187616),(4848092148039344000,47.9,1418187616),(5478623705960852000,390,1418187616),(8140845578042856000,39,1418187616),(5438687370349259000,88,1418187616),(13805945922347448000,8.8,1418187616),(11024536505834158000,54.6112060546875,1418187616),(924611717538063500,54.6112060546875,1418187616),(12176129164800047000,54.6112060546875,1418187616),(13973560578559859000,54.6112060546875,1418187616),(9069799255453575000,54.6112060546875,1418187616),(673788639311822200,54.6112060546875,1418187616),(4212101817470065700,54.6112060546875,1418187616),(9904339372573927000,54.6112060546875,1418187616),(11567934081272046000,54.6112060546875,1418187616),(2672256545527277600,54.6112060546875,1418187616),(1465397152510534100,54.6112060546875,1418187616),(3293557955404544000,54.6112060546875,1418187616),(1447515352424098600,54.6112060546875,1418187616),(16863477761970248000,54.6112060546875,1418187616),(7288674336425909000,54.6112060546875,1418187616),(5065251567760913000,54.6112060546875,1418187616),(9905061640102273000,54.6112060546875,1418187616),(7417530935187468000,54.6112060546875,1418187616),(7734587267143796000,54.6112060546875,1418187616),(3367587328015735300,54.6112060546875,1418187616),(2719122892390496000,54.6112060546875,1418187616),(16884437635415790000,54.6112060546875,1418187616),(18023917505273858000,54.6112060546875,1418187616),(9303308746700675000,54.6112060546875,1418187616),(625523981121321600,54.6112060546875,1418187616),(5077531646803091000,54.6112060546875,1418187616),(2689778751224222700,54.6112060546875,1418187616),(13604716854324713000,0,1418187616),(7938646743037302000,54.6112060546875,1418187616),(7535168736638986000,54.6112060546875,1418187616),(1833026553585239000,1,1418187616),(2386250044397541000,0.1,1418187616),(8426735824233240000,54.6112060546875,1418187616),(17925447252925620000,54.6112060546875,1418187616),(1887115770332307000,54.6112060546875,1418187616),(508242786119895000,NaN,1418187616),(14892102699910190000,10997,1418187616),(10175263243088185000,82,1418187616),(852451786174898800,10,1418187616)] failed. Reason: The query uses a MySQL feature which is not yet supported by MemSQL. Supported MySQL query features are described at http://developers.memsql.com/docs/2.6

**Comment by carlsverre** [comment]
Thanks for the bug report CheeriosJo.  Will look into this soon.

**Comment by CheeriosJo** [comment]
Thanks! @carlsverre #shutterstock-memsql

**Comment by amckinley** [comment]
Hi @CheeriosJo,
Can you give me a little more repro information? I'm having a hard time getting NaN values into statsd. All the following examples are already detected and handled correctly:

```
12 Dec 16:20:46 - DEBUG: Bad line: NaN,c in msg "foo:NaN|c"
12 Dec 16:20:51 - DEBUG: Bad line: nan,c in msg "foo:nan|c"
12 Dec 16:20:56 - DEBUG: Bad line: ,c in msg "foo:|c"
12 Dec 16:21:04 - DEBUG: Bad line: null,c in msg "foo:null|c"
12 Dec 16:21:11 - DEBUG: Bad line: false,c in msg "foo:false|c"
12 Dec 16:21:16 - DEBUG: Bad line: inf,c in msg "foo:inf|c"
12 Dec 16:21:21 - DEBUG: Bad line: bar,c in msg "foo:bar|c"
```

Are you using some of statsd's derived metrics, like percentiles, average, standard deviation, etc? What version of statsd are you using?

**Comment by jhiza** [comment]
Yes we are using percentiles:
https://github.com/etsy/statsd/blob/master/exampleConfig.js#L37-L40

for example

**Comment by amckinley** [comment]
We've pushed a fix for this to master: https://github.com/memsql/memsql-statsd/commit/c6f052011bd90943d8f43243cd912fb8c93e12b6

We'll deploy the new version to npm today.
