### ISSUE TITLE
Support for configuration of multiple StatsD prefixes

### ISSUE THREAD

**Issue by seanpquig** [memsql/memsql-statsd#2]
Hey guys,

It's Sean from Shutterstock.  We've coordinated on a few MemSQL plugin feature requests in the past.  

We currently send all StatsD metrics prefixed with **stats** to our MemSQL cluster, but we recently wanted to create alerts against our MemSQL cluster that reference metrics prefixed with **statsd** such as **statsd.pool_2.hostname.numStats**.  Is there an easy way we could support configuring multiple StatsD prefixes in this plugin?  Or perhaps you know of an alternative way to achieving this functionality?

Thanks a lot.

**Comment by carlsverre** [comment]
Hey Sean,
The current prefix system is simple, it just prefixes all metrics with a certain string before sending it onwards.  I believe you are asking to conditionally prefix a metric with either "stats" or "statsd" depending on which metric it is, is that correct?  I think this would be fairly easy to do if you re-use the whitelist/blacklist code to specify different prefixes for different matching queries.

The relevant section of code is here
https://github.com/memsql/memsql-statsd/blob/master/lib/analytics_cache.js#L101

You could add a map to the statsd config where the key is a regex that matches certain metrics and the value is the prefix to use with matching metrics.  It sounds like that might end up being quite complicated to update though.

**Comment by seanpquig** [comment]
Thanks Carl.  This ended up not being an issue.

**Comment by carlsverre** [comment]
Great!  Thanks for the update.
